export const ReserveWatchReceiverAbi = [
  {
    type: "function",
    name: "updateAttestation",
    stateMutability: "nonpayable",
    inputs: [
      { name: "attestationHash", type: "bytes32" },
      { name: "reserveUsd", type: "uint256" },
      { name: "liabilitySupply", type: "uint256" },
      { name: "coverageBps", type: "uint256" },
      { name: "asOfTimestamp", type: "uint256" },
      { name: "breakerTriggered", type: "bool" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "updateAttestationV2",
    stateMutability: "nonpayable",
    inputs: [
      { name: "attestationHash", type: "bytes32" },
      { name: "reserveUsd", type: "uint256" },
      { name: "navUsd", type: "uint256" },
      { name: "liabilitySupply", type: "uint256" },
      { name: "coverageBps", type: "uint256" },
      { name: "asOfTimestamp", type: "uint256" },
      { name: "breakerTriggered", type: "bool" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "lastAttestationHash",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "bytes32" }],
  },
  {
    type: "function",
    name: "lastReserveUsd",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "lastNavUsd",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "lastLiabilitySupply",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "lastCoverageBps",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "lastAsOfTimestamp",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "mintingPaused",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "minCoverageBps",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
] as const
